update to brokerapi v11
the dependabot update to `existingvolumebroker-0.138.0` requires to switch everything over
to brokerapi v11

fixes:
```
./main.go:333:3: cannot use services (variable of type Services) as existingvolumebroker.Services value in argument to existingvolumebroker.New: Services does not implement existingvolumebroker.Services (wrong type for method List)
		have List() []"github.com/pivotal-cf/brokerapi/v10/domain".Service
		want List() []"github.com/pivotal-cf/brokerapi/v11/domain".Service
```

fly-by:
remove deprectated ioutil usage